development:
  host: localhost
  database: agribuddy_development

test:
  host: localhost
  database: agribuddy_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>